/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment2;
import java.util.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author kseni
 */
public class GameBoard extends javax.swing.JFrame {

    /**
     * Creates new form GameBoard
     */
    private int size;
    private Map<Integer, JButton> board;
    private JPanel bPanel;
    private JPanel gamePanel;
    
    private JLabel player1L;
    private JLabel player2L;

    private Player player1;
    private Player player2;
    
    public GameBoard(int size) {
        this.size = size;
        board = new HashMap<>();
        player1 = new Player("PLAYER 1");
        player2 = new Player("PLAYER 2");        
        setTitle("Game board : " + size + " x " + size);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);        setLocationRelativeTo(null);
        setSize(700,700);
        setVisible(true);
        setLocationRelativeTo(null);
        
        //initComponents();
        createBoard();
        //pack();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void createBoard(){
        
        gamePanel = new JPanel();
        gamePanel.setLayout(new BorderLayout());
        
        bPanel = new JPanel();
        bPanel.setLayout(new GridLayout(size, size));
        
        player1L = new JLabel(player1.getName());
        //player1L.setForeground(Color.BLUE);
        
        player2L = new JLabel(player2.getName());
        //player2L.setForeground(Color.RED);
        
        //int points = 0;
//        bPanel.setSize(200, 500);
        for (int i = 0; i < size; i++){
            for (int j = 0; j<size; j++){
                JButton field = new JButton ("0");
                field.setFont(new Font("Arial",Font.PLAIN, 15));
                //field.setSize(100, 100);
                field.setBackground(Color.GREEN);
                bPanel.add(field);
                int position = i*size+j;
                board.put(position, field);
            }
        }
        gamePanel.add(player1L, BorderLayout.WEST);
        gamePanel.add(bPanel, BorderLayout.CENTER);
        gamePanel.add(player2L, BorderLayout.EAST);
        add(gamePanel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GameBoard().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
