/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment2;

import javax.swing.*;
/**
 *
 * @author kseni
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        threeXthree = new javax.swing.JButton();
        sevenXseven = new javax.swing.JButton();
        fiveXfive = new javax.swing.JButton();
        GameName = new javax.swing.JLabel();
        ChooseBoard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(153, 153, 255));

        threeXthree.setBackground(new java.awt.Color(102, 0, 255));
        threeXthree.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        threeXthree.setText("3x3");
        threeXthree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        threeXthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeXthreeActionPerformed(evt);
            }
        });

        sevenXseven.setBackground(new java.awt.Color(102, 51, 255));
        sevenXseven.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        sevenXseven.setText("7x7");
        sevenXseven.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sevenXseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenXsevenActionPerformed(evt);
            }
        });

        fiveXfive.setBackground(new java.awt.Color(102, 51, 255));
        fiveXfive.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        fiveXfive.setText("5x5");
        fiveXfive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fiveXfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveXfiveActionPerformed(evt);
            }
        });

        GameName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        GameName.setText("Four Game");

        ChooseBoard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        ChooseBoard.setText("Choose the board size");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(GameName)
                    .addComponent(ChooseBoard)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(threeXthree, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(fiveXfive, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(sevenXseven, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(GameName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChooseBoard)
                .addGap(36, 36, 36)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threeXthree, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sevenXseven, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveXfive, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void threeXthreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeXthreeActionPerformed
        // TODO add your handling code here:
        dispose();
        
        GameBoard gameBoard = new GameBoard(3);
        gameBoard.setVisible(true);
        
    }//GEN-LAST:event_threeXthreeActionPerformed

    private void sevenXsevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenXsevenActionPerformed
        // TODO add your handling code here:
        dispose();
        
        GameBoard gameBoard = new GameBoard(7);
        gameBoard.setVisible(true);
    }//GEN-LAST:event_sevenXsevenActionPerformed

    private void fiveXfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveXfiveActionPerformed
        // TODO add your handling code here:
        dispose();
        
        GameBoard gameBoard = new GameBoard(5);
        gameBoard.setVisible(true);
    }//GEN-LAST:event_fiveXfiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChooseBoard;
    private javax.swing.JLabel GameName;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton fiveXfive;
    private javax.swing.JButton sevenXseven;
    private javax.swing.JButton threeXthree;
    // End of variables declaration//GEN-END:variables
}
